### ISSUE TITLE
server ban player

### ISSUE THREAD

**Issue by alvin0611** [IzzelAliz/Arclight#1504] opened 2024-09-30 16:17 UTC
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Arclight
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Forge 复现

### Arclight 版本

arclight-fabric-1.21-1.0.0-SNAPSHOT.jar

### Java 版本 | 操作系统

java version "22.0.1" 2024-04-16

### 相关 Mod/插件 的名称及版本

```raw
nothing
```

### 错误描述

the server will ban the player who use /kill, also cant go through from the end back to overworld. the ban is like that player cant use chat and cant place block

### 复现步骤

1. use /kill
2. go through the portal from the end back to overworld

### 报错信息

![image](https://github.com/user-attachments/assets/e6700398-c747-460c-aac0-fd6ef290a920)

**Comment by qyl27** [comment] 2024-10-01 03:05
Duplicate of #1398 and #1411 .

**Closed as completed by qyl27** 2024-10-01 03:05 UTC
Labels: Status: Triage
